apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-project-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: final-project
  template:
    metadata:
      labels:
        app: final-project
    spec:
      containers:
        - name: final-project
          image: fabianrc2810/final-project:32840c710a6631aba3b01967cbb6429db1fc93e1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
